//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supplier_dashboard_1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisation_items
    {
        public int requisation_item_id { get; set; }
        public Nullable<int> requisation_no { get; set; }
        public Nullable<int> requisation_item_code { get; set; }
        public string requisation_desc { get; set; }
        public string quantity { get; set; }
        public string brand { get; set; }
        public string price_suggester { get; set; }
    
        public virtual customers_requisation customers_requisation { get; set; }
        public virtual item item { get; set; }
    }
}
